name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '2.1.2'

    - name: Install dependencies
      run: poetry install

    - name: Run check
      run: make check

    - name: Run tests
      run: make test
